shinpi/config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get "/gambling/rankings", to: "pages#gambling_rankings"
  get "/gambling/profiles", to: "pages#gambling_profiles"
  get "/politics/rankings", to: "pages#politics_rankings"
  get "/finance/rankings", to: "pages#finance_rankings"
  get "/finance/profiles", to: "pages#finance_profiles"
  get "/politics/profiles", to: "pages#politics_profiles"
  get "/sports/rankings", to: "pages#sports_rankings"
  get "/sports/profiles", to: "pages#sports_profiles"
  get "/sports/rooms", to: "pages#sports_rooms"
  get "/finance/rooms", to: "pages#finance_rooms"
  get "/politics/rooms", to: "pages#politics_rooms"
  get "/gambling/rooms", to: "pages#gambling_rooms"
  get "/profiles", to: "pages#profiles"


  resources :rooms do
    resources :privileges
    resources :activities
    resources :posts
  end

  resources :users, only: [] do
    resources :profiles
    get "/spectations", to: "pages#spectations"
    get "/rooms", to: "users#rooms"
  end

  root to: 'pages#shinpi'



end

shinpi/app/views/pages/finance_profiles.html.erb
<h1>Finance Profiles</h1>

<% @finance_profiles.each do |t| %>
<section class="well">
<figure>
<img class="img-rounded img-responsive" src="http://www.webdesignforums.net/img/wdf_avatar.jpg">
<figcaption class="text-center"> <%= User.find_by(id: t.user_id).name  %> <br><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i> </figcaption>
</figure>
<dl class="dl-horizontal">
<dt>Joined:</dt>
<dd><%= time_ago_in_words(User.find_by(id: t.user_id).created_at)%></dd>
<dt>Posts:</dt>
<dd><%= Post.where(user_id: t.user_id).count || 0 %></dd>
<dt>Spectators:</dt>
<dd>
<% all = 0 %>
<% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
<% Room.where(id: g.room_id).each do |f| %>

<% all +=  f.head_count.to_i %>
<% end %>
<% end %>
<%= all %>
</dd>
<dt>Revenue:</dt>
<dd>
  <% all = 0 %>
  <% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
  <% Room.where(id: g.room_id).each do |f| %>
  <% all +=  f.confirmed_revenue.to_i %>
  <% end %>
  <% end %>
  $<%= all %>
</dd>
<%= link_to "Visit Profile",  user_profile_path(@user,t), class: 'btn btn-primary btn-sm',id:"profile-button" %>
</dl>
</section>
<% end %>

shinpi/app/views/pages/finance_rankings.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>

<h1>Finance Rooms</h1>

<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @finance_rankings.each do |t| %>
    <div>
      <tr>
      <td><%= link_to t.name, room_path(t.id) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/finance_rooms.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>

<h1>Finance Rooms</h1>
 
<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @finance_rooms.each do |t| %>
    <div>
      <tr>
      <td><%= link_to t.name, room_path(t.id) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/gambling_profiles.html.erb
<h1>Finance Profiles</h1>

<% @gambling_profiles.each do |t| %>
<section class="well">
<figure>
<img class="img-rounded img-responsive" src="http://www.webdesignforums.net/img/wdf_avatar.jpg">
<figcaption class="text-center"> <%= User.find_by(id: t.user_id).name  %> <br><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i> </figcaption>
</figure>
<dl class="dl-horizontal">
<dt>Joined:</dt>
<dd><%= time_ago_in_words(User.find_by(id: t.user_id).created_at)%></dd>
<dt>Posts:</dt>
<dd><%= Post.where(user_id: t.user_id).count || 0 %></dd>
<dt>Spectators:</dt>
<dd>
<% all = 0 %>
<% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
<% Room.where(id: g.room_id).each do |f| %>

<% all +=  f.head_count.to_i %>
<% end %>
<% end %>
<%= all %>
</dd>
<dt>Revenue:</dt>
<dd>
  <% all = 0 %>
  <% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
  <% Room.where(id: g.room_id).each do |f| %>
  <% all +=  f.confirmed_revenue.to_i %>
  <% end %>
  <% end %>
  $<%= all %>
</dd>
<%= link_to "Visit Profile",  user_profile_path(@user,t), class: 'btn btn-primary btn-sm',id:"profile-button" %>
</dl>
</section>
<% end %>

shinpi/app/views/pages/gambling_rankings.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>

<h1>Gambling Rankings</h1>

<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @gambling_rankings.each do |t| %>
    <div>
      <tr>
      <td><%= link_to t.name, room_path(t.id) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/gambling_rooms.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>
<h1>Gambling Rooms</h1>
 
<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @gambling_rooms.each do |t| %>
    <div>
      <tr>
      <td><%= link_to t.name, room_path(t.id) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <% if !current_user %>
      <div class="headerings">
      <h1>Welcome!</h1>
      <h4>New Users</h4>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
      </p>
      </div>
      <% else %>
      <h1> Welcome <%=current_user.name%>, what are you looking for? </h1>
     <% end %>
     <% end %>
    </div>
  </div>
<div class="room-cards">
<% if current_user %>
<div class="gambling">
<h2>Gambling</h2><br>
<% @gambling.each do |room| %>
  <div class="card" style="width: 18rem">
  <%= image_tag ("/assets/mockup/samurai-thumbnail.jpg"), class: "card-img-top"%>
  <div class="card-body">
    <h5 class="card-title"><%= room.name %></h5>

    <a href="#" class="btn btn-primary"><%= room.room_type.capitalize %> Room</a>
  </div>
</div>
<% end %><br>
</div>
<div class="sports">
<h2>Sports</h2><br>
<% @sports.each do |room| %>
  <div class="card" style="width: 18rem;">
<%= image_tag ("/assets/mockup/samurai-thumbnail.jpg"), class: "card-img-top"%>
  <div class="card-body">
    <h5 class="card-title"><%= room.name %></h5>

    <a href="#" class="btn btn-primary"><%= room.room_type.capitalize %> Room</a>
  </div>
</div>
<% end %><br>
</div>
<div id="task-form" style="display:none;"></div>

<div class="finance">
<h2>Finance</h2><br>
<% @finance.each do |room| %>
  <div class="card" style="width: 18rem;">
  <%= image_tag ("/assets/mockup/samurai-thumbnail.jpg"), class: "card-img-top"%>
  <div class="card-body">
    <h5 class="card-title"><%= room.name %></h5>
    <a href="#" class="btn btn-primary"><%= room.room_type.capitalize %> Room</a>
  </div>
</div>
<% end %>
</div>
<% end %>
</div>

shinpi/app/views/pages/politics_profiles.html.erb
<h1>Finance Profiles</h1>

<% @politics_profiles.each do |t| %>
<section class="well">
<figure>
<img class="img-rounded img-responsive" src="http://www.webdesignforums.net/img/wdf_avatar.jpg">
<figcaption class="text-center"> <%= User.find_by(id: t.user_id).name  %> <br><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i> </figcaption>
</figure>
<dl class="dl-horizontal">
<dt>Joined:</dt>
<dd><%= time_ago_in_words(User.find_by(id: t.user_id).created_at)%></dd>
<dt>Posts:</dt>
<dd><%= Post.where(user_id: t.user_id).count || 0 %></dd>
<dt>Spectators:</dt>
<dd>
<% all = 0 %>
<% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
<% Room.where(id: g.room_id).each do |f| %>

<% all +=  f.head_count.to_i %>
<% end %>
<% end %>
<%= all %>
</dd>
<dt>Revenue:</dt>
<dd>
  <% all = 0 %>
  <% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
  <% Room.where(id: g.room_id).each do |f| %>
  <% all +=  f.confirmed_revenue.to_i %>
  <% end %>
  <% end %>
  $<%= all %>
</dd>
<%= link_to "Visit Profile",  user_profile_path(@user,t), class: 'btn btn-primary btn-sm',id:"profile-button" %>
</dl>
</section>
<% end %>

shinpi/app/views/pages/politics_rankings.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>

<h1>Politics Rankings</h1>

<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @politics_rankings.each do |t| %>
    <div>
      <tr>
      <td><%= link_to t.name, room_path(t.id) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/politics_rooms.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>
<h1>Politics Rooms</h1>
 
<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @politics_rooms.each do |t| %>
    <div>
      <tr>
      <td><%= t.name %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/profile.html.erb
<h1> User Profile </h1>
<%= form_for(@user) do |f| %>
   <%= render 'shared/error_messages' %>

   <%= f.label :name %>
   <%= f.text_field :name, class: 'form-control' %>

   <%= f.label :email %>
   <%= f.email_field :email, class: 'form-control' %>

   <%= f.label :bio %>
   <%= f.text_area :bio %>

   <% f.label :industry %>
   <%= f.checkbox "Finance" %>
   <%= f.checkbox "Technology" %>
   <%= f.checkbox "Betting" %>
   <%= f.checkbox "Other" %>
   <h5>Years of Experience</h5>
   <%= f.number_field :experience_in_industry %>

   <h5>Links</h5>
   <p>GitHub</p>
   <%= f.text_field :github %>
   <p>Linkedin</p>
   <%= f.text_field :linkedin %>
   <p>Seeking Alpha</p>
   <%= f.text_field :s_a %>

   <%= f.label :password %>
   <%= f.password_field :password, class: 'form-control' %>

   <%= f.label :password_confirmation, "Confirmation" %>
   <%= f.password_field :password_confirmation, class: 'form-control' %>

   <%= f.submit "Save changes", class: "btn btn-primary" %>
 <% end %>

shinpi/app/views/pages/profiles.html.erb
<h1>Room Owner Profiles</h1>
<% @profiles.each do |t| %>
<div class="profiles">
<section class="well">
<figure>
<img class="img-rounded img-responsive" src="http://www.webdesignforums.net/img/wdf_avatar.jpg">
<figcaption class="text-center"> <%= User.find_by(id: t.user_id).name  %> <br><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i> </figcaption>
</figure>
<dl class="dl-horizontal">
<dt>Joined:</dt>
<dd><%= time_ago_in_words(User.find_by(id: t.user_id).created_at)%></dd>
<dt>Posts:</dt>
<dd><%= Post.where(user_id: t.user_id).count || 0 %></dd>
<dt>Spectators:</dt>
<dd>
<% all = 0 %>
<% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
<% Room.where(id: g.room_id).each do |f| %>

<% all +=  f.head_count.to_i %>
<% end %>
<% end %>
<%= all %>
</dd>
<dt>Revenue:</dt>
<dd>
  <% all = 0 %>
  <% Privilege.where(user_id: t.user_id, owner:true).each do |g| %>
  <% Room.where(id: g.room_id).each do |f| %>
  <% all +=  f.confirmed_revenue.to_i %>
  <% end %>
  <% end %>
  $<%= all %>
</dd>
<%= link_to "Visit Profile",  user_profile_path(@user,t), class: 'btn btn-primary btn-sm',id:"profile-button" %>
</dl>
</section>
<% end %>
</div>

shinpi/app/views/pages/sports_rankings.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>

<h1>Finance Rooms</h1>

<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @sports_rankings.each do |t| %>
    <div>
      <tr>
      <td><%= link_to t.name, room_path(t.id) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>

shinpi/app/views/pages/sports_rooms.html.erb
<head>
  <script>
  $(document).ready(function () {
  $('#dtBasicExample').DataTable();
  $('.dataTables_length').addClass('bs-select');
  });
  </script>
</head>
<h1>Sports Rooms</h1>
 
<table id="dtBasicExample" class="table table-striped sortable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th class="th-sm">Name
      </th>
      <th class="th-sm">Type
      </th>
      <th class="th-sm">Spectators
      </th>
      <th class="th-sm"> Room Price
      </th>
      <th class="th-sm">Confirmed Revenue($)
      </th>
      <th class="th-sm"> Owner Name
      </th>
      <th class="th-sm"> Room Start Date
      </th>
    </tr>
  </thead>
  <tbody>
    <% @sports_rooms.each do |t| %>
    <div>
      <tr>
      <td><%=link_to(t.name,room_path(t.id)) %></td>
      <td><%= t.room_type.capitalize %></td>
      <td><%= t.head_count %></td>
      <td><%= t.room_price %></td>
      <td><%= t.confirmed_revenue %></td>
      <td><%= t.owner_name %></td>
      <td><%= t.created_at %></td>
      </div>
      <tr>
  <% end %>
</table>