shinpi/config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get "/gambling/rankings", to: "pages#gambling_rankings"
  get "/gambling/profiles", to: "pages#gambling_profiles"
  get "/politics/rankings", to: "pages#politics_rankings"
  get "/finance/rankings", to: "pages#finance_rankings"
  get "/finance/profiles", to: "pages#finance_profiles"
  get "/politics/profiles", to: "pages#politics_profiles"
  get "/sports/rankings", to: "pages#sports_rankings"
  get "/sports/profiles", to: "pages#sports_profiles"
  get "/sports/rooms", to: "pages#sports_rooms"
  get "/finance/rooms", to: "pages#finance_rooms"
  get "/politics/rooms", to: "pages#politics_rooms"
  get "/gambling/rooms", to: "pages#gambling_rooms"
  get "/profiles", to: "pages#profiles"


  resources :rooms do
    resources :privileges
    resources :activities
    resources :posts
  end

  resources :users, only: [] do
    resources :profiles
    get "/spectations", to: "pages#spectations"
    get "/rooms", to: "users#rooms"
  end

  root to: 'pages#shinpi'



end

shinpi/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

shinpi/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_action :authenticate_user!

  def new
    @user = current_user
    @profile = Profile.new
  end

  def index
    @user = User.find_by(id: params[:user_id])
    @profile = @user.profile
  end

  def show
    @user = User.find_by(id: params[:user_id])
    @profile = @user.profile
  end


  def create
    if !current_user.profile
    @user = current_user
    @profile = Profile.new
    @user.profile = @profile

     params[:profile].each do |t|
      @profile[t[0]] = t[1]
    @profile.save
  end

    redirect_to root_path
  else
    redirect_to new_user_profile_path(@user,@profile)
  end
end


  def edit
    @user = current_user
    @profile = Profile.where(user_id: @user.id)[0]
  end

  def update
    @user = current_user
    @profile = Profile.where(user_id: @user.id)[0]
     params[:profile].each do |t|
      @profile[t[0]] = t[1]
      @profile.save
    end
      if @profile.save
    redirect_to root_path
  else
    redirect_to root_path
  end
end





  private

  def profile_params
    params.require(:profile).permit(:bio,:experience_in_industry,:industry,:linkedin,:github,:seeking_alpha,:website)
  end

end

shinpi/app/views/profiles/edit.html.erb
<h1>Edit User Profile</h1>
<div class="new-profile">
<%= form_for [@user,@profile] do |f| %>
<%= f.label :bio %><br>
<%= f.text_area :bio, class:"form-control" %>
<br>
<%= f.label :industry %><br>
<%= f.text_area :industry, class:"form-control", value: @profile.industry %>
<br>
<%= f.label :experience_in_industry %><br>
<%= f.number_field :experience_in_industry, :step => 0.5, class:"form-control", value: @profile.experience_in_industry %>
<br>
<%= f.label :github %><br>
<%= f.text_area :github, class:"form-control", placeholder: @profile.github || "Github" %>
<br>
<%= f.label :linkedin %><br>
<%= f.text_area :linkedin, class:"form-control",placeholder: @profile.github || "Linkedin Linke"  %>
<br>
<%= f.label :seeking_alpha %><br>
<%= f.text_area :seeking_alpha, class:"form-control",placeholder: @profile.github || "Seeking Alpha Site"  %>
<br>
<%= f.label :website %><br>
<%= f.text_area :website, class:"form-control",placeholder: @profile.github || "Website"  %>
<br>
<%= f.submit "Submit", class: 'btn btn-primary'  %>
<% end %>
</div>

shinpi/app/views/profiles/index.html.erb
<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
   
<div class="profile-container">
  <h1>User Profile Index</h1>
    <div class="span3 well">
        <center>
        <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" class="img-circle"></a>
        <h3><%= @user.name %></h3>
        <h3>Confirmed Revenue: $<%= @profile.total_confirmed_revenue || 0 %></h3>
        <em>click my face for more</em>
		</center>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title" id="myModalLabel"> More About <%= @user.name %> </h4>
                    </div>
                <div class="modal-body">
                    <center>
                    <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
                    <h3 class="media-heading"><%= @user.name %><small>USA</small></h3>
                    <span><strong>Industry: </strong></span>
                    <span class="label label-warning"> <%= @profile.industry %> </span><br>
                    <span><strong>Experience: </strong></span>
                    <span class="label label-success"> <%= @profile.experience_in_industry %> </span><br>
                    <span><strong>User since: </strong></span>
                    <span class="label label-warning"> <%= time_ago_in_words(@user.created_at) %> </span><br>
                    <span><strong> Total Spectators: </strong></span>
                    <span class="label label-success"> <%= @profile.total_spectators || 0 %> People </span><br>
                    <span><strong> Total Revenue: </strong></span>
                    <span class="label label-warning"> $<%= @profile.total_confirmed_revenue || 0 %> </span>
                    </center>
                    <hr>
                    <center>
                    <p class="text-left"><strong>Bio: </strong><br>
                        <%= @profile.bio %>
                      </p>
                    <br>
                    </center>
                </div>
                <div class="modal-footer">
                    <center>
                    <%= link_to "Edit", edit_user_profile_path(@user,@profile), class: 'btn btn-primary btn-lg' %>
                    <button type="button" class="btn btn-default" data-dismiss="modal">I've heard enough about <%= @user.name %></button>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

shinpi/app/views/profiles/new.html.erb
<h1>New Profile Page</h1>
<div class="new-profile">


<%= form_for [@user,@profile] do |f| %>
<%= f.label :bio %><br>
<%= f.text_area :bio, class:"form-control" %>
<br>
<%= f.label :industry %><br>
<%= f.text_area :industry, class:"form-control" %>
<br>
<%= f.label :experience_in_industry %><br>
<%= f.number_field :experience_in_industry, :step => 0.5, class:"form-control"  %>
<br>
<%= f.label :github %><br>
<%= f.text_area :github, class:"form-control" %>
<br>
<%= f.label :linkedin %><br>
<%= f.text_area :linkedin, class:"form-control" %>
<br>
<%= f.label :seeking_alpha %><br>
<%= f.text_area :seeking_alpha, class:"form-control" %>
<br>
<%= f.label :website %><br>
<%= f.text_area :website, class:"form-control" %>
<br>
<%= f.submit "Submit", class: 'btn btn-primary'  %>

<% end %>
</div>

shinpi/app/views/profiles/show.html.erb
<head>
   <tdnk href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<div class="profile-container">
  <h1><%= @user.name%>'s Profile</h1>
  <% if current_user.id === @user.id %>
  <%= link_to "Create a Room", new_room_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to "Edit Profile", edit_user_profile_path(@user,@profile), class: 'btn btn-primary btn-lg' %>
  <% end %>
    <div class="span3 well">
        <center>
        <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" class="img-circle"></a>
        <h3><%= @user.name %></h3>
        <h3>Confirmed Revenue: $<%= @profile.total_confirmed_revenue || 0 %></h3>
        <em>click my face for more</em>
		</center>
    </div>

    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title" id="myModalLabel"> More About <%= @user.name %> </h4>
                    </div>
                <div class="modal-body">
                  <left class="left-profile-modal">
                    <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
                    <h3 class="media-heading"><%= @user.name %><br><small>USA</small></h3>
                      <table class="profile-table">
                      <tr>
                         <th>Industry</th>
                         <td><%=@profile.industry%></td>
                      </tr>
                        <tr>
                         <th>Experience</th>
                          <td><%=@profile.experience_in_industry%></td>
                         </tr>
                         <tr>
                         <th>User Since</th>
                         <td><%= time_ago_in_words(@user.created_at)%></td>
                         </tr>
                         <tr>
                         <th>Total Spectators</th>
                          <td><%= @profile.total_spectators || 0 %> People</td>
                         </tr>
                         <tr>
                         <th>Total Revenue</th>
                         <td>$<%= @profile.total_confirmed_revenue%></td>
                         </tr>
                         <tr>
                         <th>Github</th>
                              <td><%= @profile.github%></td>
                         </tr>
                         <tr>
                         <th>Linkedin</th>
                         <td><%= @profile.linkedin%></td>
                         </tr>
                         <tr>
                         <th>Biography</th>
                         <td><%= @profile.bio%></td>
                         </tr>
                      </table>
                    </left>
                </div>
                <div class="modal-footer">
                    <center>
                    <button aria-hidden="true"type="button" class="close" data-dismiss="modal" >Exit</button>
                    </center>
                </div>
            </div>
        </div>
    </div>
    <br>
    <h3>More Users Like <%= @user.name %>:</h3>