shinpi/config/routes.rb
Rails.application.routes.draw do


  devise_for :users

  get "/gambling/rankings", to: "pages#gambling_rankings"
  get "/gambling/profiles", to: "pages#gambling_profiles"
  get "/politics/rankings", to: "pages#politics_rankings"
  get "/finance/rankings", to: "pages#finance_rankings"
  get "/finance/profiles", to: "pages#finance_profiles"
  get "/politics/profiles", to: "pages#politics_profiles"
  get "/sports/rankings", to: "pages#sports_rankings"
  get "/sports/profiles", to: "pages#sports_profiles"
  get "/sports/rooms", to: "pages#sports_rooms"
  get "/finance/rooms", to: "pages#finance_rooms"
  get "/politics/rooms", to: "pages#politics_rooms"
  get "/gambling/rooms", to: "pages#gambling_rooms"
  get "/profiles", to: "pages#profiles"


  resources :rooms do
    resources :privileges
    resources :activities
    resources :posts
  end

  resources :users, only: [] do
    resources :profiles
    get "/spectations", to: "pages#spectations"
    get "/rooms", to: "users#rooms"
  end

  root to: 'pages#shinpi'



end

shinpi/app/models/room.rb
class Room < ApplicationRecord
  has_many :privileges
  has_many :activities
  has_many :posts
end

shinpi/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

def new
  @room = Room.new
end


def create
  @room = Room.new
  @user = current_user
  @profile = @user.profile
  if @user && @profile
    @room.save
    @privilege = Privilege.new
    @privilege[:user_id] = @user.id
    @privilege[:room_id] = @room.id
    @privilege[:public] = false
    @privilege[:owner] = true
    @privilege[:allowed] = true
    @privilege.save

    params[:room].each do |t|
      @room[t[0]] = t[1]
    end
    @room.user_id = current_user.id
    @room.save
    redirect_to room_path(@room)
  end

end

def show
  @user = current_user
  @room = Room.find_by(id: params[:id])
  @post = Post.new
  @owner = User.find_by(id: @room.user_id)
  @user_privilege = Privilege.find_by(room_id: @room.id, user_id: @user.id)
  @user_private = Privilege.where(room_id: @room.id, owner: true)[0]
  @activities = Activity.where(room_id: @room.id)
end

def index
  @rooms = Room.all
end

def edit
end

def destroy
end





private
def room_params
  params.require(:room).permit(:room_type,:name,:thumbnail_text,:thumbnail_img)
end
end

shinpi/app/views/rooms/edit.html.erb
<h1> Room Edit </h1>
 

shinpi/app/views/rooms/index.html.erb
 
<h1> Room Index </h1>
<% @rooms.each do |room| %>
<% setter = room.id %>

<% end %>

shinpi/app/views/rooms/new.html.erb
 
<h1> Room New </h1>
<% if !current_user.profile %>
<h1>Please Create a Profile First</h1>
<% end %>

<% if current_user.profile && current_user.profile.experience_in_industry.to_i < 2 %>
<div class="shinpi-headings">
<h2>You cannot create a Room for that yet. Your years of experience must be longer than <%= current_user.profile.experience_in_industry %> year </h2>
<div>
<% end %>
<% if current_user.profile && current_user.profile.experience_in_industry.to_i > 2 %>
<div class="shinpi-headings">
<h1>Room Application</h1>
<%= form_for(@room) do |f| %>
<div class="room-form">
<br>
<h4>Room Type:</h4>
<%= f.text_area :room_type, class: 'form-control' %>
<br>
<h4>Room Name:</h4>
<%= f.text_area :name, class:"form-control", id:"room-tango"  %>
<br>
<h4>Room Description:</h4>
<%= f.text_area :description, class:"form-control"  %>
<br>
<h4>Room Thumbnail Description:</h4>
<%= f.text_area :thumbnail_text, class:"form-control"  %>
<br>
<h4>Room Price:</h4>
<%= f.number_field :room_price, :step => 1, class:"form-control"  %> / month
<br>
<h4>Room Owner (Must be Profile Holder):</h4>
<%= f.text_area :owner_name, :value => current_user.name, class:"form-control" %>
<br>
<%= f.submit "Submit Application for Room", class: 'btn btn-primary' %>
</div>
<% end %>
</div>
<% end %>

shinpi/app/views/rooms/show.html.erb
<% if !@user_privilege %>
<div id="room-show-head" class="shinpi-headings">
<h1><u> <%= @room.name %></u></h1>
<h3>Please Sign in to View Content from <%= @room.name %></h3>
<h5>Confirmed Revenue: $<%= @room.confirmed_revenue || 0 %>  </h5>
<%= link_to "Get Access Privileges", new_room_privilege_path(@room), class: "btn btn-primary btn-md" %>
</div>
<% end %>

<% if @user_privilege %>
<div id="room-show-head" class="shinpi-headings">
<h1> <%= @room.name %></h1>
<% if @user_private == @user_privilege %>
<h5>Owner Room Wager</h5>
<%= link_to "New Room Wager", new_room_activity_path(@room), class: "btn btn-primary btn-md"  %>
<% end %>
<h5>Confirmed Revenue: $<%= @room.confirmed_revenue || 0 %>  </h5>
<%= link_to "View Access Privileges", room_privilege_path(@room,@user), class: "btn btn-primary btn-md" %>
</div>
<section class="row clearfix">
<section class="col-md-12 column">
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#"> <%= @room.name %> </a>
</div>
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
<form class="navbar-form navbar-left" role="search">
<div class="form-group">
<input id="search-bar"type="text" class="form-control" placeholder="Search in this post...">
</div>
<button type="submit" class="btn btn-default"><i class="fa fa-search"></i>Search</button>
</form>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
<% if @activities %>
<div class="actvities-room">
  <center>
    <h3>Open Room Wagers</h3>
  <table>
    <tr id="act-heads">
    <th >Symbol</th>
    <th>Wager</th>
    <th>Expires</th>
    </tr>
  <% @activities.each do |x| %>
  <tr>
  <th id="principal"><%= x.principal %></th>
  <% if x.buy %>
  <th id="green-man">$<%= x.wager_size %></th>
  <% end %>
  <% if x.sell %>
  <td id="red-man">$<%= x.wager_size %></td>
  <% end %>
  <% if x.wager %>
  <td id="yellow-man">$<%= x.wager_size %></td>
  <% end %>
  <td><%= x.wager_contract_end %></td>
  <% end %>
  </tr>
  </table>
  <span id="glossary"><p>Red = Sell</p>//
  <p>Green = Buy</p>//
  <p>Yellow = Wager</p></span>
  <h3>Open Activities</h3>
  </center>

</div>
<% end %>
<% if @room.posts %>
<% @room.posts.each do |t| %>
<% @user = User.find_by(id: t.user_id) %>
<% profile = Profile.find_by(user_id: @user.id) %>
<div class="row clearfix">
<div class="col-md-12 column">
<div class="panel panel-default">
<div class="panel-heading">
  <time class="pull-right">
  <i class="fa fa-calendar"></i><%= time_ago_in_words(t.created_at)%>
  </time>
  <abbr title="count of posts in this topic"><%= t.id %></abbr>
<section class="panel-title">
<section class="pull-left" id="id">
</section>
</section>
</div>
<section class="row panel-body">
<section class="col-md-9">
<h2> <i class="fa fa-smile-o"></i> <%= @user.name.capitalize %> 's Post </h2>
<hr> <%= t.content %>
</section>
<section id="user-description" class="col-md-3 ">
<section class="well">
<div class="dropdown">
<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-cricle"><%= @user.name %></i><span class="caret"></span></a>
<ul class="dropdown-menu" role="menu">
<li><a href="#"><i class="fa fa-user"></i> See profile</a></li>
<li><a href="#"><i class="fa fa-envelope"></i> Send PM</a></li>
<li><a href="#"><i class="fa fa-code"></i>View all Articles</a></li>
<li><a href="#"><i class="fa fa-th-list"></i>View all Posts</a></li>
<li class="divider"></li>
<li><a href="#"><i class="fa fa-plus"></i>Add to contact List</a></li>
<li class="divider"></li>
<li><a href="#"><i class="fa fa-cogs"></i> Manage User (for adminstrator)</a></li>
</ul>
</div>
		<!-- block for poster  -->
<figure id="whiskey-tango-figure">
<img class="img-rounded img-responsive" src="http://www.webdesignforums.net/img/wdf_avatar.jpg" >
<figcaption class="text-center"><%= @user.name %>  <br><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i> </figcaption>
</figure>
<dl class="dl-horizontal">
<dt>Joined</dt>
<dd><%= time_ago_in_words(@user.created_at) %> ago</dd>
<dt>Revenue:</dt>
<dd>$<%= profile.total_confirmed_revenue || 0 %></dd>
<dt>Spectators:</dt>
<dd><%= profile.total_spectators || 0 %> People</dd>
</dl>
</section>
</section>
</section>
<div class="panel-footer">
<div class="row">
<section class="col-md-2 ">
<i class="fa fa-thumbs-up "></i><a href="#"> Thanks </a>| <i class="fa fa-warning "></i><a href="#"> Report </a>
</section>
<section id="thanks" class="col-md-6">
<small><a href="#" data-toggle="tooltip" title="You and david,ehsan,john doe">  who L<i class="fa fa-heart "></i>ve this!</a> </small><br>

</section>
<section class="col-md-4">
<span class="fa-stack">
<i class="fa fa-quote-right fa-stack-1x"></i>
<i class="fa fa-comment-o fa-lg fa-stack-1x"></i>
</span>
<button class="btn btn-success btn-xl" data-toggle="modal" data-target="#approvalModal">
  Reply
</button>
<button class="btn btn-success btn-xl" data-toggle="modal" data-target="#approvalModal">
  Edit
</button>
</section>
</div>
</div>
</div>
</div>
</div>
<% end %>
<% else %>
<h1>No Posts in this Group yet</h1>
<% end %>
<div id="post-forum"class="shinpi-headings">
<%= form_for [@room,@post] do |l| %>
<%= l.label :content %>
<%= l.text_area :content, class:"form-control" %>
<%= l.submit "Post in Room", class: 'btn btn-primary btn-md' %>
<% end %>
</div>
</section>
</section>
</section>
<% end %>
<footer class="page-footer">

  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/"> Astsumari </a>
  </div>
</footer>